import  Cars from "@/components/ui/cars"; 
import { Metadata } from "next";

export const metadata: Metadata = { 
  title: "Carros",
  description: "Generated by create next app",
  icons:  "/mottor.ico"
};

const Car = () => {
  return ( 
    <div>
      <Cars/>
    </div>
   );
}
 
export default Car;