import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mottor",
  description: "Generated by create next app",
  icons:  "/mottor.ico"
};

export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
    
      <body className={inter.className}  >
        {children}
        <Header />
        <Footer /> 
      </body>
    </html>
  );
}
