import Motos from "@/components/ui/motos" ;
import { Metadata } from "next";

export const metadata: Metadata = { 
  title: "Motos",
  description: "Generated by create next app",
  icons:  "/mottor.ico"
};
const Moto = () => {
  return ( 
    <div>
      <Motos/>
    </div>
   );
}
 
export default Moto;