import  Trucks from "@/components/ui/trucks"; 
import { Metadata } from "next";

export const metadata: Metadata = { 
  title: "Caminhão",
  description: "Generated by create next app",
  icons:  "/mottor.ico"
};

function Truck() {
  return (
    <div>
      <Trucks />
    </div>
  );
}
 
export default Truck;