import { Card } from "@/components/ui/card";
import { Metadata } from "next";
import Image from "next/image";


export const metadata: Metadata = { 
  title: "Jetta GLI 2024 | Carros | Mottor ",
  description: "Generated by create next app",
  icons:  "/mottor.ico "
};

const News01cars = () => {
  return (
    <div className=" flex-col container  mx-auto mt-40 mb-24 px-4 flex items-center">
      <div className="flex justify-start items-center gap-3 bg-gray-400 rounded-lg text-black p-6 mb-1 mx-auto w-[500px] sm:w-2/4 h-2/4 ">
        <Image
          src="/clemilson.jpg"
          alt="Imagem do Clemilson"
          width={42}
          height={42}
          className="rounded-full  overflow-hidden"
        />
        <h1 className="font-bold text-orange-600">Clemilson Chaves</h1>
        <p>22/05/2024</p>
        <p>05:13</p>
      </div>

      <Card className=" flex flex-col text-start items-center bg-gray-800 justify-center p-6  mt-20 mb-9 gap-8 mx-auto w-[500px] sm:w-2/4 h-2/4 ">
        <h1 className="flex text-black font-bold uppercase mt-4 mb-3">
          Novo Jetta GLI: Performance, Estilo e Tecnologia em um Sedan Esportivo
        </h1>
        
        <p>
        A Volkswagen apresentou recentemente a nova versão do Jetta GLI,
        trazendo uma combinação impressionante de performance, estilo e
        tecnologia. Este modelo, que já era conhecido por sua esportividade e
        refinamento, chega agora ainda mais robusto e atraente, prometendo
        conquistar tanto entusiastas de carros quanto aqueles que buscam um
        sedan sofisticado e potente.
        </p>

        <div>
        <Image
           src="/jetta.jpg"
           alt="Imagem do jetta"
           width={360}
           height={360}
           className="rounded-lg"
        >

        </Image>
        <p className="text-xxs  text-black">Fonte: VolksWagen Automóveis</p>
        </div>
        
        <p>
        Design Externo e Estilo O novo Jetta GLI
        exibe um design exterior atualizado, que combina elegância e
        agressividade. A frente do carro foi redesenhada, apresentando uma grade
        mais larga e faróis LED mais afilados, que conferem ao veículo uma
        aparência mais moderna e imponente. Os detalhes em vermelho na grade e
        nos freios, exclusivos da versão GLI, realçam o caráter esportivo do
        sedan. As rodas de liga leve de 18 polegadas, também exclusivas do GLI,
        complementam o visual dinâmico.
        </p>
        
        <div>
        <Image
           src="/jetta5.jpg"
           alt="Imagem do jetta"
           width={360}
           height={360}
           className="rounded-lg" 
        >

        </Image>
        <p className="text-xxs  text-black">Fonte: VolksWagen Automóveis</p>
        </div>

        <p>
        Na traseira, o difusor redesenhado e as
        saídas de escape cromadas duplas não apenas melhoram a estética, mas
        também contribuem para a performance aerodinâmica do veículo.
        Performance e Mecânica Debaixo do capô, o Jetta GLI é alimentado por um
        motor 2.0 TSI, que gera impressionantes 230 cavalos de potência e 35,7
        kgfm de torque. Esse motor é acoplado a uma transmissão automática de
        dupla embreagem DSG de 7 velocidades, que proporciona mudanças de marcha
        rápidas e precisas. A tração é dianteira, mas o Jetta GLI vem equipado
        com um diferencial de deslizamento limitado, que melhora a aderência e a
        estabilidade, especialmente em curvas. A suspensão esportiva é outro
        destaque, com ajuste independente nas quatro rodas, garantindo um
        equilíbrio perfeito entre conforto e desempenho.
        </p>

        <div>
        <Image
           src="/jetta4.jpg"
           alt="Imagem do jetta"
           width={360}
           height={360}
           className="rounded-lg" 
        >

        </Image>
        <p className="text-xxs  text-black">Fonte: VolksWagen Automóveis</p>
        </div>


        <p>
        O sistema de freios foi
        aprimorado para oferecer respostas mais rápidas e eficientes, essencial
        para um carro com o espírito esportivo do GLI. Interior e Conforto Por
        dentro, o Jetta GLI não decepciona. O acabamento premium inclui bancos
        esportivos revestidos em couro com costuras vermelhas, um painel de
        instrumentos digital configurável de 10,25 polegadas, e um sistema de
        infotainment com tela sensível ao toque de 8 polegadas. O sistema de som
        Beats de alta qualidade garante uma experiência sonora imersiva. Os
        ocupantes do veículo desfrutam de um espaço interno generoso, com
        assentos confortáveis e bem suportados. O ar-condicionado automático
        dual-zone, teto solar panorâmico e iluminação ambiente ajustável são
        apenas alguns dos itens que elevam o nível de conforto e conveniência do
        Jetta GLI. 
        </p>

        <div>
        <Image
           src="/jetta2.jpg"
           alt="Imagem do jetta"
           width={360}
           height={360}
           className="rounded-lg" 
        >

        </Image>
        <p className="text-xxs  text-black">Fonte: VolksWagen Automóveis</p>
        </div>

        <p>
        Tecnologia e Segurança Em termos de tecnologia, o novo Jetta
        GLI vem equipado com uma série de recursos avançados. Entre eles estão o
        controle de cruzeiro adaptativo, sistema de monitoramento de ponto cego,
        assistente de permanência em faixa, frenagem de emergência autônoma, e
        um sistema de câmera de ré com sensores de estacionamento. O sistema de
        infotainment é compatível com Apple CarPlay e Android Auto, permitindo a
        integração perfeita de smartphones. Além disso, a Volkswagen oferece um
        conjunto de serviços conectados, incluindo navegação em tempo real e
        controle remoto de algumas funções do veículo através de um aplicativo
        móvel. Conclusão O novo Jetta GLI é um sedan que combina o melhor dos
        dois mundos: a elegância e o conforto de um carro de passeio com a
        performance e a emoção de um esportivo. 
        </p>
        
        <div>
        <Image
           src="/jetta3.jpg"
           alt="Imagem do jetta"
           width={360}
           height={360}
           className="rounded-lg" 
        >

        </Image>
        <p className="text-xxs  text-black">Fonte: VolksWagen Automóveis</p>
        </div>

        <p>
        Com seu design atualizado, motor
        potente, interior luxuoso e uma vasta gama de tecnologias de segurança e
        conveniência, o Jetta GLI se destaca como uma opção atraente para quem
        busca um veículo versátil e emocionante. A Volkswagen, mais uma vez,
        mostra sua capacidade de inovar e atender às demandas dos consumidores
        mais exigentes, consolidando o Jetta GLI como um dos principais modelos
        em sua categoria.
        </p>
      </Card>
    </div>
  );


}
 
export default News01cars;