import QuemSomos from "@/components/ui/quemSomos";
import { Metadata } from "next";

export const metadata: Metadata = { 
  title: "Quem somos",
  description: "Generated by create next app",
  icons:  "/mottor.ico"
};
const QuemSomo = () => {
  return ( 
    <div>
      <QuemSomos/>
    </div>
   );
}
 
export default QuemSomo;