import React from "react";
import Cars from "@/components/ui/cars";
import Motos from "@/components/ui/motos";
import Trucks from "@/components/ui/trucks";
import { Metadata } from "next";

export const metadata: Metadata = { 
  title: "Home",
  description: "Generated by create next app",
  icons:  "/mottor.ico "
};

export default function Home() {
  return (
    <div className="mt-12"> 
      <Cars/>

      <Motos/>

      <Trucks/> 

      
    </div>
  );
}
